#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
DIR=/app

HOOKS_PATH="deploy/pre-build-buildpack"

COMMAND=$(cat <<EOF

if [ -f $DIR/HOOKS_PATH ]; then
	echo "-----> pre-deploy hooks found"
    /bin/bash -c <<< cat $DIR/HOOKS_PATH
fi
EOF
sleep 1 # wait so that docker run has not exited before docker attach
)

echo "-----> Running pre-build-buildpack hooks"

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")

docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
