#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Running pre-deploy hooks"

DIR=/app

HOOKS_PATH="deploy-hooks/pre-deploy"

COMMAND=$(cat <<EOF

if [ -f $DIR/$HOOKS_PATH ]; then
	echo "-----> pre-deploy hooks found"
    /bin/bash -c <<< cat $DIR/$HOOKS_PATH
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
